title: USDM Native Area Aggregations
description: Weekly US Drought Monitor (USDM) data aggregated to US Census native area boundaries
author: R. Kyle Bocinsky
url: "https://native-resilience.github.io/usdm-aiannh/"  # Your GitHub Pages URL
baseurl: "/usdm-aiannh"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# minima:
#   skin: classic
